byway/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("web.urls",namespace="web")),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path
from web.views import Home,Course,Courses


app_name = "web"


urlpatterns = [
    path('',Home,name="homepage"),
    path('course/<int:pk>',Course,name="coursepage"),
    path('courses/<str:category>',Courses,name="coursespage"),
]

web/models.py
from django.db import models
from django.core.validators import MinValueValidator,MaxValueValidator
from decimal import Decimal
from django.core.exceptions import ValidationError
from decimal import Decimal, ROUND_HALF_UP


PERCENTAGE_VALIDATOR = [MinValueValidator(0), MaxValueValidator(100)]

def validate_half_or_full_percentage(value):
    if Decimal(value) % 1 not in (Decimal('0.0'), Decimal('0.5')):
        raise ValidationError(f"Only full or half percentages are allowed. You provided {value}.")


class Language(models.Model):
    name=models.CharField(max_length=255)

    class Meta:
        db_table="web_Language"
        ordering=["name"]
        verbose_name="course_Language"
        verbose_name_plural="course_Languages"

    def __str__(self):
        return self.name

class Category(models.Model):
    name=models.CharField(max_length=255)
    logo=models.FileField(upload_to="category/icons/")
    
    class Meta:
        db_table="web_Category"
        ordering=["name"]
        verbose_name="course_category"
        verbose_name_plural="course_categories"

    def __str__(self):
        return self.name    
    
class Author(models.Model):
    name=models.CharField(max_length=255)
    profile_image=models.FileField(upload_to="course/authors/")

    class Meta:
        db_table="web_Author"
        ordering=["name"]
        verbose_name="Author"
        verbose_name_plural="Authors"

    def __str__(self):
        return self.name    


class Course(models.Model):
    title = models.CharField(max_length=255)
    card_title = models.CharField(max_length=28)
    image = models.ImageField(upload_to="course/images/")
    thumbnail_image = models.ImageField(upload_to="course/thumbnailimages/")
    description = models.TextField()
    rating = models.FloatField(validators=[MinValueValidator(1.0), MaxValueValidator(5.0)])
    rated_customers_count = models.PositiveIntegerField(default=0)
    total_hours = models.DurationField()
    author = models.ForeignKey("web.Author", on_delete=models.CASCADE, blank=True, null=True)
    category = models.ForeignKey("web.Category", on_delete=models.DO_NOTHING, null=True, blank=True, related_name="courses")
    languages = models.ManyToManyField("web.Language")
    number_of_lectures = models.PositiveIntegerField()
    mrp_price = models.DecimalField(max_digits=5, decimal_places=2)
    next_session_date = models.DateField(null=True, blank=True)  
    discount_percentage = models.DecimalField(
        max_digits=4,
        decimal_places=1, 
        default=Decimal(0),
        validators=PERCENTAGE_VALIDATOR + [validate_half_or_full_percentage]
    )

    def formatted_discount_percentage(self):
        if self.discount_percentage == self.discount_percentage.to_integral_value():
            return int(self.discount_percentage)
        return float(self.discount_percentage)

    
    @property
    def course_price(self):
        discount_multiplier = Decimal('1') - (self.discount_percentage / Decimal('100'))
        return self.mrp_price * discount_multiplier
    

    def get_similar_courses(self):
        return Course.objects.filter(
            category=self.category
        ).exclude(id=self.id).order_by('?')[:4]

    def total_decimal_hours(self):
        total_seconds = int(self.total_hours.total_seconds())
        hours, remainder = divmod(total_seconds, 3600)
        minutes, _ = divmod(remainder, 60)
        decimal_hours = hours + minutes / 60
        rounded_hours = round(decimal_hours, 2)
        
        if rounded_hours.is_integer():
            return int(rounded_hours)
        return rounded_hours

    def formatted_price(self):
        if self.mrp_price == self.mrp_price.to_integral_value():
            return int(self.mrp_price)
        return float(self.mrp_price)
    

    def formatted_course_price(self):
        course_price = self.course_price
        rounded_price = course_price.quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)

        if rounded_price == rounded_price.to_integral_value():
            return int(rounded_price)
        return float(rounded_price)

    
    class Meta:
        db_table="web_Course"
        ordering=["-id"]
        verbose_name="course"
        verbose_name_plural="courses"

    def __str__(self):
        return self.title    
    

web/views.py
from django.shortcuts import render,get_object_or_404
from django.db.models import Count
from web.models import Course as Coursemodel, Category

def Home(request):
    courses = Coursemodel.objects.all().order_by('-rating', '-rated_customers_count')[:4]
    categories = Category.objects.annotate(total_courses=Count('courses'))[:4]
    context = {
        "login": False,
        "courses": courses,
        "categories": categories
    }
    return render(request, "index.html", context=context)


def Course(request,pk):
    course_content=get_object_or_404(Coursemodel.objects.filter(pk=pk))
    similar_courses = course_content.get_similar_courses()
    context={
        "login":True,
        "course":course_content,
        "similar_courses":similar_courses
    }
    return render(request,"singlepage.html",context=context)


def Courses(request,category):
    if(category=="all"):
        courses_list= Coursemodel.objects.all().order_by('-rating', '-rated_customers_count')
    else:    
       courses_list = Coursemodel.objects.filter(category__name=category)
    context={
        "login":True,
        "courses":courses_list,
        "slug":category
    }
    return render(request,"courses.html",context=context)

templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		{% load static %}

		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Byway</title>
		<link rel="stylesheet" href="{% static '/css/style.css' %}" />
		<link rel="stylesheet" href="{% static '/css/font.css' %}" />
		<link
			rel="shortcut icon"
			href="{% static '/images/logo.svg' %}"
			type="image/x-icon" />
	</head>
	<body>
		<header>
			<section class="wrapper">
				<section class="head">
					<div class="logo">
						<h1>
							<a href="{% url 'web:homepage' %}">
								<div class="logocontainer">
									<img
										src="{% static '/images/logo.svg' %}"
										alt="Byway logo" />
								</div>
								<span>Byway</span>
							</a>
						</h1>
					</div>
					{% if login %}
					<nav class="navbar-logined">
						<ul>
							<li>
								<a href="/">
									<img
										src="{% static '/images/wishlist.svg' %}"
										alt="Like" />
								</a>
							</li>
							<li>
								<a href="/">
									<img
										src="{% static '/images/cart.svg' %}"
										alt="cart" />
								</a>
							</li>
							<li>
								<button>
									<img
										src="{% static '/images/bell.svg' %}"
										alt="bell icon" />
								</button>
							</li>
							<li><button>J</button></li>
						</ul>
					</nav>
					{% else %}
					<nav class="navbar">
						<ul>
							<li>
								<a href="/">
									<button>
										<img
											src="{% static '/images/cart.svg' %}"
											alt="cart" />
									</button>
								</a>
							</li>
							<li>
								<a href="/">Log In</a>
							</li>
							<li>
								<a href="/">Sign Up</a>
							</li>
						</ul>
					</nav>
					{% endif %}
				</section>
			</section>
		</header>
		{% block content %} {% endblock %}
		<footer>
			<section class="wrapper">
				<section id="footer-content">
					<div class="main">
						<div class="imagecontainer">
							<h1>
								<a href="{% url 'web:homepage' %}">
									<img
										src="{% static '/images/footerlogo.svg' %}"
										alt="logo" />
								</a>
							</h1>
						</div>
						<p>
							Empowering learners through accessible and engaging
							online education. <br />
							Byway is a leading online learning platform
							dedicated to providing high-quality, flexible, and
							affordable educational experiences.
						</p>
					</div>
					<div class="get-help">
						<h5>Get Help</h5>
						<a href="/">Contact Us</a>
						<a href="/">Latest Articles</a>
						<a href="/">FAQ</a>
					</div>
					<div class="programs">
						<h5>Programs</h5>
						<a href="/">Art & Design</a>
						<a href="/">Business</a>
						<a href="/">IT & Software</a>
						<a href="/">Languages</a>
						<a href="/">Programming</a>
					</div>
					<div class="Contact-us">
						<div class="inner">
							<h5>Contact Us</h5>
							<p>Address: 123 Main Street, Anytown, CA 12345</p>
							<a href="tel:+(123) 456-7890"
								>Tel: +(123) 456-7890</a
							>
							<a href="mailto:bywayedu@webkul.in"
								>Mail: bywayedu@webkul.in</a
							>
						</div>
						<div class="logos">
							<img
								src="{% static '/images/social-media.svg' %}"
								alt="contact icons" />
						</div>
					</div>
				</section>
			</section>
		</footer>
		<script src="{% static '/js/script.js' %}"></script>
	</body>
</html>

templates/courses.html
{% extends "base.html" %} {% load static %} {% block content %}
<section id="forcourses">
	<section class="wrapper">
		<section class="resusing-component-content">
			{% if courses %} {% if slug == "all" %}
			<h2>Courses</h2>
			{% else %}
			<h2>{{ slug }} Courses</h2>
			{% endif %}
			<div class="courses-cards">
				{% for course in courses %}
				<div
					class="course-price-details card"
					data-mrp="{{course.formatted_price}}"
					data-discount="{{course.formatted_discount_percentage}}">
					<a href="{% url 'web:coursepage' pk=course.pk %}">
						<div class="imagecontainer">
							<img
								src="{{course.image.url}}"
								alt="course image" />
						</div>
						<div class="course-details">
							<ul>
								<li>
									<h5>{{course.card_title}}</h5>
									<span>By {{course.author.name}}</span>
								</li>
								<li class="Ratings">
									<div class="ratingfullstar">
										<img
											src="{% static '/images/ratings.svg' %}"
											alt="ratings star" />
									</div>
									<span
										>({{course.rated_customers_count}}
										Ratings)</span
									>
								</li>
								<li>
									<span>
										{{course.total_decimal_hours}} Total
										Hours. {{course.number_of_lectures}}
										Lectures. Beginner
									</span>
								</li>
							</ul>
							<h4></h4>
						</div>
					</a>
				</div>
				{% endfor %}
			</div>
			{% else %}
			<div class="error">
				<h6>oops! No courses found.</h6>
			</div>
			{% endif %}
		</section>
	</section>
</section>
{% endblock %}

templates/index.html
{% extends "base.html" %} {% load static %} {% block content %}
<section id="spotlight">
	<section class="wrapper">
		<section class="content">
			<div class="content-left">
				<div>
					<h1>Unlock Your Potential with Byway</h1>
					<p>
						Welcome to Byway, where learning knows no bounds. We
						believe that education is the key to personal and
						professional growth, and we're here to guide you on your
						journey to success.
					</p>
				</div>

				<a href="/">Start your instructor journey</a>
			</div>
			<div class="content-right">
				<img
					src="{% static '/images/spotlight.png' %}"
					alt="join our community" />
			</div>
		</section>
	</section>
</section>
<section id="statistics">
	<section class="background">
		<section class="wrapper">
			<section class="content">
				<ul>
					<li>
						<h2>250+</h2>
						<span>Courses by our best mentors</span>
					</li>
					<li></li>
					<li>
						<h2>1000+</h2>
						<span>Courses by our best mentors</span>
					</li>
					<li></li>
					<li>
						<h2>15+</h2>
						<span>Courses by our best mentors</span>
					</li>
					<li></li>
					<li>
						<h2>2200+</h2>
						<span>Courses by our best mentors</span>
					</li>
				</ul>
			</section>
		</section>
	</section>
</section>
<section id="top-categories">
	<section class="wrapper">
		<section class="content">
			<div class="head">
				<h3>Top Categories</h3>
				<a href="/">See All</a>
			</div>
			<div class="Categories-cards">
				{% for category in categories %}
				<div class="card">
					<a
						href="{% url 'web:coursespage' category=category.name %}">
						<div class="imagebackground">
							<div class="imagecontainer">
								<img
									src="{{category.logo.url}}"
									alt="Astrology" />
							</div>
						</div>
						<h4>{{category.name}}</h4>
						<p>{{category.total_courses}} Courses</p>
					</a>
				</div>
				{% endfor %}
			</div>
		</section>
	</section>
</section>
<section id="top-courses">
	<section class="wrapper">
		<section class="content">
			<div class="head">
				<h3>Top Courses</h3>
				<a href="{% url 'web:coursespage' category='all' %}">See All</a>
			</div>
			<div class="courses-cards">
				{% for course in courses %}
				<div
					class="course-price-details card"
					data-mrp="{{course.formatted_price}}"
					data-discount="{{course.formatted_discount_percentage}}">
					<a href="{% url 'web:coursepage' pk=course.pk %}">
						<div class="imagecontainer">
							<img
								src="{{course.image.url}}"
								alt="course image" />
						</div>
						<div class="course-details">
							<ul>
								<li>
									<h5>{{course.card_title}}</h5>
									<span>By {{course.author}}</span>
								</li>
								<li class="Ratings">
									<div class="ratingfullstar">
										<img
											src="{% static '/images/ratings.svg' %}"
											alt="ratings star" />
									</div>
									<span
										>({{course.rated_customers_count}}
										Ratings)</span
									>
								</li>
								<li>
									<span>
										{{course.total_decimal_hours}} Total
										Hours. {{course.number_of_lectures}}
										Lectures. Beginner
									</span>
								</li>
							</ul>
							<h4></h4>
						</div>
					</a>
				</div>
				{% endfor %}
			</div>
		</section>
	</section>
</section>
<section id="top-instructors">
	<section class="wrapper">
		<section class="content">
			<div class="head">
				<h3>Top Instructors</h3>
				<a href="/">See All</a>
			</div>
			<div class="instructors-cards">
				<div class="card">
					<a href="/">
						<div class="imagecontainer">
							<img
								src="{% static '/images/model-5.jpg' %}"
								alt="course image" />
						</div>
						<ul class="course-details">
							<li>
								<h5>Ronald Richards</h5>
								<span>UI/UX Designer</span>
							</li>
							<li></li>
							<li class="Ratings">
								<div class="star">
									<div>
										<img
											src="{% static '/images/star.svg' %}"
											alt="ratings star" />
									</div>
									<span>4.9</span>
								</div>
								<p>2400 Students</p>
							</li>
						</ul>
					</a>
				</div>
				<div class="card">
					<a href="/">
						<div class="imagecontainer">
							<img
								src="{% static '/images/model-5.jpg' %}"
								alt="course image" />
						</div>
						<ul class="course-details">
							<li>
								<h5>Ronald Richards</h5>
								<span>UI/UX Designer</span>
							</li>
							<li></li>
							<li class="Ratings">
								<div class="star">
									<div>
										<img
											src="{% static '/images/star.svg' %}"
											alt="ratings star" />
									</div>
									<span>4.9</span>
								</div>
								<p>2400 Students</p>
							</li>
						</ul>
					</a>
				</div>
				<div class="card">
					<a href="/">
						<div class="imagecontainer">
							<img
								src="{% static '/images/model-5.jpg' %}"
								alt="course image" />
						</div>
						<ul class="course-details">
							<li>
								<h5>Ronald Richards</h5>
								<span>UI/UX Designer</span>
							</li>
							<li></li>
							<li class="Ratings">
								<div class="star">
									<div>
										<img
											src="{% static '/images/star.svg' %}"
											alt="ratings star" />
									</div>
									<span>4.9</span>
								</div>
								<p>2400 Students</p>
							</li>
						</ul>
					</a>
				</div>
				<div class="card">
					<a href="/">
						<div class="imagecontainer">
							<img
								src="{% static '/images/model-5.jpg' %}"
								alt="course image" />
						</div>
						<ul class="course-details">
							<li>
								<h5>Ronald Richards</h5>
								<span>UI/UX Designer</span>
							</li>
							<li></li>
							<li class="Ratings">
								<div class="star">
									<div>
										<img
											src="{% static '/images/star.svg' %}"
											alt="ratings star" />
									</div>
									<span>4.9</span>
								</div>
								<p>2400 Students</p>
							</li>
						</ul>
					</a>
				</div>
				<div class="card">
					<a href="/">
						<div class="imagecontainer">
							<img
								src="{% static '/images/model-5.jpg' %}"
								alt="course image" />
						</div>
						<ul class="course-details">
							<li>
								<h5>Ronald Richards</h5>
								<span>UI/UX Designer</span>
							</li>
							<li></li>
							<li class="Ratings">
								<div class="star">
									<div>
										<img
											src="{% static '/images/star.svg' %}"
											alt="ratings star" />
									</div>
									<span>4.9</span>
								</div>
								<p>2400 Students</p>
							</li>
						</ul>
					</a>
				</div>
			</div>
		</section>
	</section>
</section>
<section class="testmonial">
	<section class="content">
		<section class="wrapper">
			<div class="head">
				<h3>What Our Customer Say <br />About Us</h3>
				<div class="buttons">
					<button onclick="scrollleft()">
						<img
							src="{% static '/images/short-arrow-left.svg' %}"
							alt="leftbutton" />
					</button>
					<button onclick="scrollright()">
						<img
							src="{% static '/images/short-arrow-right.svg' %}"
							alt="rightbutton" />
					</button>
				</div>
			</div>
		</section>
		<div class="testmonial-cards">
			<div class="cards">
				<ul>
					<li class="doubleqoutes-container">
						<img
							src="{% static '/images/quotes.svg' %}"
							alt="double-quotes" />
					</li>
					<li>
						<p>
							"Byway's tech courses are top-notch! As someone
							who's always looking to stay ahead in the rapidly
							evolving tech world, I appreciate the up-to-date
							content and engaging multimedia.
						</p>
					</li>
					<li>
						<div class="imagecontainer">
							<img
								src="{% static '/images/Ellipse.png' %}"
								alt="cutomer image" />
						</div>
						<div>
							<h5>Jane Doe</h5>
							<span>Designer</span>
						</div>
					</li>
				</ul>
			</div>
			<div class="cards">
				<ul>
					<li class="doubleqoutes-container">
						<img
							src="{% static '/images/quotes.svg' %}"
							alt="double-quotes" />
					</li>
					<li>
						<p>
							"Byway's tech courses are top-notch! As someone
							who's always looking to stay ahead in the rapidly
							evolving tech world, I appreciate the up-to-date
							content and engaging multimedia.
						</p>
					</li>
					<li>
						<div class="imagecontainer">
							<img
								src="{% static '/images/Ellipse.png' %}"
								alt="cutomer image" />
						</div>
						<div>
							<h5>Jane Doe</h5>
							<span>Designer</span>
						</div>
					</li>
				</ul>
			</div>
			<div class="cards">
				<ul>
					<li class="doubleqoutes-container">
						<img
							src="{% static '/images/quotes.svg' %}"
							alt="double-quotes" />
					</li>
					<li>
						<p>
							"Byway's tech courses are top-notch! As someone
							who's always looking to stay ahead in the rapidly
							evolving tech world, I appreciate the up-to-date
							content and engaging multimedia.
						</p>
					</li>
					<li>
						<div class="imagecontainer">
							<img
								src="{% static '/images/Ellipse.png' %}"
								alt="cutomer image" />
						</div>
						<div>
							<h5>Jane Doe</h5>
							<span>Designer</span>
						</div>
					</li>
				</ul>
			</div>
			<div class="cards">
				<ul>
					<li class="doubleqoutes-container">
						<img
							src="{% static '/images/quotes.svg' %}"
							alt="double-quotes" />
					</li>
					<li>
						<p>
							"Byway's tech courses are top-notch! As someone
							who's always looking to stay ahead in the rapidly
							evolving tech world, I appreciate the up-to-date
							content and engaging multimedia.
						</p>
					</li>
					<li>
						<div class="imagecontainer">
							<img
								src="{% static '/images/Ellipse.png' %}"
								alt="cutomer image" />
						</div>
						<div>
							<h5>Jane Doe</h5>
							<span>Designer</span>
						</div>
					</li>
				</ul>
			</div>
			<div class="cards">
				<ul>
					<li class="doubleqoutes-container">
						<img
							src="{% static '/images/quotes.svg' %}"
							alt="double-quotes" />
					</li>
					<li>
						<p>
							"Byway's tech courses are top-notch! As someone
							who's always looking to stay ahead in the rapidly
							evolving tech world, I appreciate the up-to-date
							content and engaging multimedia.
						</p>
					</li>
					<li>
						<div class="imagecontainer">
							<img
								src="{% static '/images/Ellipse.png' %}"
								alt="cutomer image" />
						</div>
						<div>
							<h5>Jane Doe</h5>
							<span>Designer</span>
						</div>
					</li>
				</ul>
			</div>
		</div>
	</section>
</section>
<section id="features">
	<section class="wrapper">
		<section class="content">
			<div class="top">
				<div class="imagecontainer">
					<img
						src="{% static '/images/model-4.jpg' %}"
						alt="instructer image" />
				</div>
				<div class="details">
					<div>
						<h5>Become an Instructor</h5>
						<p>
							Instructors from around the world teach millions of
							students on Byway. We provide the tools and skills
							to teach what you love.
						</p>
					</div>
					<a href="/">
						<button>
							<span>Start Your Instructor Journey</span>
							<div class="arrow">
								<img
									src="{% static '/images/arrow-right.svg' %}"
									alt="arrow-right" />
							</div>
						</button>
					</a>
				</div>
			</div>
			<div class="bottom">
				<div class="imagecontainer">
					<img
						src="{% static '/images/model-6.jpg' %}"
						alt="instructer image" />
				</div>
				<div class="details">
					<div>
						<h5>Transform your life through education</h5>
						<p>
							Learners around the world are launching new careers,
							advancing in their fields, and enriching their
							lives.
						</p>
					</div>
					<a href="/">
						<button>
							<span>Checkout Courses</span>
							<div class="arrow">
								<img
									src="{% static '/images/arrow-right.svg' %}"
									alt="arrow-right" />
							</div>
						</button>
					</a>
				</div>
			</div>
		</section>
	</section>
</section>
{% endblock %}